# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('releaseDate', models.DateField()),
                ('publisher', models.CharField(max_length=30)),
                ('developer', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('xb1', 'Xbox One'), ('ps4', 'Playstation 4'), ('swi', 'Switch')], default='PC', max_length=3)),
                ('genre', models.CharField(choices=[('Act', 'Action'), ('Adv', 'Adventure'), ('Sho', 'Shooter')], default='Act', max_length=3)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('date_of_birth', models.DateField(blank=True)),
                ('biography', models.CharField(blank=True, max_length=1000)),
                ('is_journalist', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
