# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190305_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('12', '12'), ('16', '16'), ('18', '18')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
