# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190308_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
