# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20190315_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/gg_default.png', upload_to='profile_images/<django.db.models.fields.related.OneToOneField>/'),
        ),
    ]
