# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20190316_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='game_images/game_placeholder.png', upload_to='game_images/'),
        ),
    ]
